version: 1
name: Basic Example
workflow:
  name: default
  statuses:
    - backlog
    - ready
    - in_progress
    - blocked
    - in_review
    - done
  transitions:
    backlog:
      - ready
      - blocked
    ready:
      - in_progress
      - blocked
    in_progress:
      - in_review
      - blocked
      - ready
    blocked:
      - ready
      - in_progress
    in_review:
      - done
      - in_progress
    done: []
  start: in_progress
  end:
    - done
  special:
    blocked:
      - blocked
    active:
      - in_review
    review:
      - in_review
id_prefixes:
  ticket: T
  epic: E
